# Generated by Django 4.0 on 2021-12-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=200, max_digits=200)),
                ('sale_start', models.DateField()),
                ('sale_end', models.DateField()),
            ],
        ),
    ]
