# Generated by Django 4.0 on 2021-12-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Produc',
        ),
    ]
