# Generated by Django 4.0 on 2021-12-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_store_produc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produc',
            new_name='Product',
        ),
    ]
