# Generated by Django 4.0 on 2021-12-31 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shoppingcartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='shopping_cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.shoppingcart'),
            preserve_default=False,
        ),
    ]
